---
- hosts: all
  become: yes

  tasks:
    - name: "Install PostgreSQL packages"
      apt:
        name:
          - postgresql-common
          - curl
          - ca-certificates
        state: present

    - name: "Download PostgreSQL key"
      shell: "curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc"

    - name: "Add PostgreSQL repository"
      shell: 'echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'

    - name: "Remove conflicting file"
      shell: "sudo rm /etc/apt/sources.list.d/pgdg.sources"

    - name: "Update package cache"
      apt:
        update_cache: yes

    - name: "Install PostgreSQL"
      apt:
        name: postgresql
        state: present

    - name: "Check PostgreSQL version"
      shell: "psql --version"

    - name: "Access PostgreSQL"
      shell: "sudo -u postgres psql"
      args:
        executable: /bin/bash

    - name: "Show PostgreSQL version"
      shell: "SELECT version();"
      args:
        executable: psql
        
    - name: "Check PostgreSQL service status"
      systemd:
        name: postgresql
        state: started
        enabled: yes
