---
- name: Check the status of services on all servers
  hosts: my_servers
  gather_facts: no
  tasks:
    - name: Check status of all services
      shell: |
        services=(nginx apache2 mysql sshd)
        for service in "${services[@]}"; do
          if systemctl list-units --full -all | grep -Fq $service; then
            if systemctl is-active $service >/dev/null 2>&1; then
              echo -e "\e[32mService $service is running\e[0m"
            else
              echo -e "\e[31mService $service is not running\e[0m"
            fi
          else
            echo -e "\e[35mService $service does not exist\e[0m"
          fi
        done
      register: service_status

    - name: Print service status
      debug:
        msg: "{{ service_status.stdout_lines }}"
